# Site settings
title: AGY
header-img: img/home-bg.jpg
email: andrewgy8@gmail.com
copyright_name: One line at a time
description: "A site to document discoveries, techniques, and host my resume."
baseurl: ""
url: "https://andrewgy8.github.io/"
twitter_username: SBootstrap
github_username:  andrewgy8
facebook_username:  andrew.grahamyooll
email_username:  andrewgy8@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
